repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        name: Lint with Ruff
        name: Lint with Ruff
        args: [--fix]
        stages: [pre-commit]
        always_run: true
        stages: [pre-commit]
        always_run: true
      - id: ruff-format
        name: Format with Ruff
        stages: [pre-commit]
        always_run: true
  - repo: local
    hooks:
      - id: custom-pre-commit
        name: Custom Pre-Commit Hook
        entry: bash -c 'pre-commit run --all-files && git diff --cached --quiet || (git add . && git commit --amend --no-edit --no-verify)'
        language: system
        stages: [pre-commit]
        always_run: true
        pass_filenames: false
