version: "3.9"
services: 
  mysql:
    # 容器名(以后的控制都通过这个)
    container_name: mysql5.7
    # 重启策略
    restart: always
    image: mysql:5.7
    ports:
      - "3309:3306"
    volumes:
      # 挂挂载配置文件
      - /D/mysql57/conf:/etc/mysql/conf.d
      # 挂载日志
      - /D/mysql57/logs:/logs
      # 挂载数据
      - /D/mysql57/data:/var/lib/mysql
      # 数据库初始化脚本，当Mysql容器首次启动时，会在 /docker-entrypoint-initdb.d目录下扫描 .sh，.sql，.sql.gz类型的文件。如果这些类型的文件存在，将执行它们来初始化一个数据库；
      - .:/docker-entrypoint-initdb.d/
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=80M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]
    environment:
      # root 密码
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    # 部署配置
    deploy:
      #在此常规示例中，服务被限制为不超过 1024M 内存和（4CPU）， 并保留了内存和 CPU 时间（始终可用）。  
      resources:
        limits:
          cpus: '4'
          memory: 1024M
        reservations:
          cpus: '1'
          memory: 200M  
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s    
    networks:
      app-net:
        aliases:
          - mysqlhost
        
  # 后台服务
  fast:
    container_name: fast
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      
    environment:
      PYTHONPATH: /app
      DB_HOST: 192.168.20.43 # nedd change your own host
      DB_PORT: 3309
    networks:
      app-net:
    depends_on:
      - mysql  
    # tty: true 
networks:
  app-net:  