

# node镜像
FROM node:16.18.1-slim as node16

WORKDIR /app/web

COPY . .

# 设置淘宝npm镜像
RUN npm config set registry http://r.cnpmjs.org
# 安装依赖
RUN npm install

RUN npm run build

FROM  node16 as build-web

RUN  echo deb  [trusted=yes] http://mirrors.aliyun.com/debian/ bullseye main non-free contrib > /etc/apt/sources.list

RUN apt update

RUN apt install nginx -y

RUN apt install systemctl -y
# 构建nginx
# FROM nginx:1.23:alpine as nginx
# 移除nginx容器的default.conf文件、nginx配置文件
# RUN rm /etc/nginx/conf.d/default.conf
# RUN rm /etc/nginx/nginx.conf
# 把主机的nginx.conf文件复制到nginx容器的/etc/nginx文件夹下
COPY ./nginx/nginx.conf /etc/nginx/
# 拷贝前端vue项目打包后生成的文件到nginx下运行
# COPY  /app/web/dist /app/web/
RUN useradd -s /sbin/nologin -M nginx

RUN id nginx

# 使用daemon off的方式将nginx运行在前台保证镜像不至于退出
# CMD ["nginx", "-g", "daemon off;"]
CMD [ "systemctl","start","nginx" ]
EXPOSE 5173