

FROM node:16-alpine as node16

WORKDIR /app/web

COPY ./web .

RUN npm config set registry https://registry.npmmirror.com

RUN npm install

RUN  npm run build


FROM nginx:alpine
COPY --from=node16 /app/web/ /app/web/
