

# node镜像
FROM node:16-alpine as node16

WORKDIR /app/web

COPY ./web .
#设置淘宝npm镜像
RUN npm config set registry https://registry.npmmirror.com
#安装依赖
RUN npm install

# 安装依赖
RUN  npm run build


FROM nginx:alpine
COPY --from=node16 /app/web/ /app/web/
